[package]
name = "ptconceal"
version = "0.1.0"
edition = "2024"

[package.metadata.windows]
subsystem = "console"

[dependencies]
clap = { version="4.5", features=["derive"] }
walkdir = "2.5.0"
zip = "4.3.0"
